apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: tcc
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: tcc-operator-controller-manager
  namespace: openshift-operators